# Generated by Django 6.0.1 on 2026-02-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
